if [[ -s "${ZDOTDIR:-$HOME}/.zprezto/init.zsh" ]]; then
  source "${ZDOTDIR:-$HOME}/.zprezto/init.zsh"
fi

source /Users/rainevi/.zshsecrets

export LC_CTYPE=en_US.UTF-8
export LC_ALL=en_US.UTF-8

alias vim="mvim -v"
alias svim="sudo mvim -v"
alias v="vim"
alias irc="mosh raine@vilja -- screen -rd irc"
alias json="python -mjson.tool"
alias jt="json"
alias lcc='fc -ln -1 | awk "{\$1=\$1}1" ORS="" | pbcopy' # copy last command
alias goog="google"
# alias ack="ag"

alias nisd="npm install --save-dev"
alias nis="npm install --save"

alias noderepl="node ~/noderepl/myrepl.js"

eval "$(gh alias -s)"
eval "$(fasd --init auto)"

alias j='fasd_cd -d'     # cd, same functionality as j in autojump
alias jj='fasd_cd -d -i' # cd with interactive selection
alias v='f -e "mvim -v"' # quick opening files with vim
alias o='a -e open'      # quick opening files with xdg-open

function restart-audio; {
  sudo kill `ps -ax | grep 'coreaudiod' | grep 'sbin' | awk '{print $1}'`
}

function curlj {
  curl -s "$@" | jt
}

# URL encode something and print it.
function url-encode; {
  setopt extendedglob
  echo "${${(j: :)@}//(#b)(?)/%$[[##16]##${match[1]}]}"
}

# Search google for the given keywords.
function google; {
  open "http://www.google.com/search?q=`url-encode "${(j: :)@}"`"
}

function beautify; {
  uglifyjs "$@" -b -o "$@"
}

function trim-empty; {
  convert "$1" -fuzz "1%" -trim +repage "$1"
}

# alias buh="cut -d\  -f3- | bunyan"
# alias buh='awk '\''{$1=$2=""; gsub(/^[ ]+/,"", $0); print $0; system("") }'\'' | bunyan'
# alias buh="sed -l 's/.*app\[web\..*\]\: //' | bunyan"
alias buh="grep --line-buffered --color=none 'app\[web.\d\+\]' | sed -l 's/.*app\[web\..*\]\: //' | bunyan"

# Change directory to the current Finder directory
cdf() {
  target=`osascript -e 'tell application "Finder" to if (count of Finder windows) > 0 then get POSIX path of (target of front Finder window as text)'`
  if [ "$target" != "" ]; then
    cd "$target"; pwd
  else
    echo 'No Finder window found' >&2
  fi
}

indir() { (cd "$1" && shift && eval "$@"); }

PATH=$PATH:$HOME/.rvm/bin # Add RVM to PATH for scripting
PATH=$PATH:$HOME/bin
PATH=$PATH:"/usr/local/heroku/bin"
PATH=$HOME/.cabal/bin:$PATH

source /Users/rainevi/.zsh/zaw/zaw.zsh
bindkey '^R' zaw-history
bindkey '^L' zaw-ack
# bindkey '^' zaw-recent-branches
bindkey -M filterselect '^R' down-line-or-history
bindkey -M filterselect '^S' up-line-or-history
bindkey -M filterselect '^E' accept-search

zstyle ':filter-select:highlight' matched fg=green
# zstyle ':filter-select' max-lines 10
zstyle ':filter-select' case-insensitive yes # enable case-insensitive
zstyle ':filter-select' extended-search yes # see below

export EDITOR="mvim -v"
source /Users/rainevi/.rvm/scripts/rvm

export SBT_OPTS="-Xss2M -Xmx1024M -XX:MaxPermSize=256M"

export GOPATH=$HOME/go
export PATH=$PATH:$GOPATH/bin
eval "`npm completion`"
eval "$(gulp --completion=zsh)"
